### ISSUE TITLE
Problems setting up on Home Assistant

### ISSUE THREAD

**Issue by aracdin** [GeoffAtHome/lightwaverf-home-assistant-switch#1]
Any suggestions on the following would be welcome!
Home Assistant 0.84.2 running on a Raspberry Pi I get "Invalid Config The following components and platforms could not be set up: lightwave Please check your config."If I run the UI Config checker I get "Configuration Valid!".
The relevant section of my config is:

lightwave:
  host: 192.168.1.128
  switches:
      R1D1:
        name: Hearts

2018-12-18 20:10:35 ERROR (MainThread) [homeassistant.setup] Error during setup of component lightwave
Traceback (most recent call last):
  File "/srv/homeassistant/lib/python3.5/site-packages/homeassistant/setup.py", line 145, in _async_setup_component
    hass, processed_config)
  File "/srv/homeassistant/lib/python3.5/site-packages/homeassistant/components/lightwave.py", line 39, in async_setup
    lights = config[DOMAIN][CONF_LIGHTS]
KeyError: 'lights'

**Comment by aracdin** [comment]
OK - I found an answer to this. You have to have *both* switches *and* lights in your configuration.yaml - then it is happy. When I tried it with only either switches *or* lights, it failed

**Comment by GeoffAtHome** [comment]
Interesting. The validation should allow for switches, lights or both. The
following should all be validate:

lightwave:
host: 192.168.1.128
switches:
R1D1:
name: Hearts

OR

lightwave:
host: 192.168.1.128
lights:
R1D1:
name: Hearts

OR

lightwave:
host: 192.168.1.128
lights:
R1D1:
name: Hearts
switches:
R1D1:
name: Hearts

No validation is done for duplicate names.

I will check the validation again, add some test cases, and update as
necessary.
